---
- name: specialized-tarmac-1
  stash: 126RwaHn4MDekLWfUYfiqcVbiQHapwDSAT9vZZS15HLqfDJh
  kusamaStash: FP6NJ41XMsHb2t7ijRhrtNW9mmNkRp9jMfw5Nwakvz9xNXE
- name: 🔒stateless_money-5🔒
  stash: 14Vh8S1DzzycngbAB9vqEgPFR9JpSvmF1ezihTUES1EaHAV
  kusamaStash: HZvvFHgPdhDr6DHN43xT1sP5fDyzLDFv5t5xwmXBrm6dusm
- name: KeepNode-Carbon
  stash: 13BeUcLu7hzSTaoKpEtpdqiXKZz6yVfT9exKH6JuTW8RQQvJ
  kusamaStash: FDDy3cQa7JXiChYU2xq1B2WUUJBpZpZ51qn2tiN1DqDMEpS
- name: starks-staking
  stash: 12mHfQJGXreUmuxuP2u4qLeytfdK3qkSJpMKxBQm8xmor3kd
  kusamaStash: EXS1FwCt9YvUMpqqrG7BUUonhoFDkqnHXPrHfSCATYvQCUc
- name: DrNo-sv-validator-1
  stash: 14gYRjn6fn5hu45zEAtXodPDbtaditK8twoWUXFi6DsLwd31
  kusamaStash: GcQXL1HgF1ZETZi3Tw3PoXGWeXbDpfsJrrgNgwxde4uoVaB
- name: 🔱-Masternode24-🔱
  stash: 14Q74NU7dG4uxiHTSCSZii5T1Y368cm7BNVNeRWmEuoDUGXQ
  kusamaStash: FyRaMYvPqpNGq6PFGCcUWcJJWKgEz29ZFbdsnoNAczC2wJZ
- name: Cable-X
  stash: 12HgRTrU7VP8jJPHXmpn9x22CYh5esTm4qvcJ8qtPpzoBbQv
  kusamaStash: H4Szoc2sxXxBTF1x88pDj9DCYERFvn4oqzQNsV7y89FnD1g
- name: Genesis Lab
  stash: 13K6QTYBPMUFTbhZzqToKcfCiWbt4wDPHr3rUPyUessiPR61
  kusamaStash: DuRV4MSm54UoX3MpFe3P7rxjBFLfnKRThxG66s4n3yF8qbJ
- name: 🍒 RYABINA 🍒 6
  stash: 1pKc7abu9Cm9YqoMeUFqdMBUxKJVuVUFPRcjpxcyKvjkx5m
  kusamaStash: GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d
- name: PDP_Validator
  stash: 16Y3FmTiJ3ZYAUZrf5rZtxrQJzcHsDBdscpu2zgMD2xN6NY7
  kusamaStash: J7MmkYX4dJzUbNnU9ccemPFbxtsyaSgFVwAGMxx8k9Lf5cu
- name: archipel-validator-1
  stash: 16aFDVsp6zd6VxUSgd34es3r23nWRkoj3NdLTS5Fk1Ez9MU1
  kusamaStash: HKnRS3RryHjzTHGu42u6BtVp2cNuYoRVnrUJGeRAKqagsKY
- name: 🐑 Hodl_dot_farm 🐑
  stash: 11VR4pF6c7kfBhfmuwwjWY3FodeYBKWx7ix2rsRCU2q6hqJ
  kusamaStash: D3bm5eAeiRezwZp4tWTX4sZN3u8nXy2Fo21U59smznYHu3F
- name: MantraDAO
  stash: 14B2ArWoQKrZy6mcHF6St6GKajTX1WzUAqpQhiVs7Bkq8n7W
  kusamaStash: HhZkxUEceUTr4FYNUAZECizfd5QLVKMdfZAL1eY3xPAPmwA
- name: ◎◉ finalbits
  stash: 14NGUTHPtUvjbJttSF4qYmX8mUKk75UweWsL3GZyHw4ue2pv
  kusamaStash: DmTzGAndAch8kXngopH69bcQCjYTukbp5Vh9SpJyiGfouwp
- name: NeNa 🌻
  stash: 131Y21vAVYxm7f5xtaV3NydJRpig3CqyvjTyFM8gMpRbFH1T
  kusamaStash: GhNL9Mi5KiL3Ge2jv4jUdncipZNnUFALbzmwg8QqwjxJxcp
- name: Polkadot Validator
  stash: 152rhiuVCzb2ehkTnga29tWwe8dRFKS5ERBvzSKS6ndtc7vt
  kusamaStash: Dwq62USrcGMwZpJ4uNXR3Q6EMWxuyiwa91gYNN6Ekp9RMN6
- name: AGx1
  stash: 13ujCsf3t2YAdAhcpcEFVoJAPRYzMLHUHEnLroQp41sJCSnm
  kusamaStash: DVasGX5qBMrCwNM8SnLyFrRpeniAwAsWe2noN6jPdx1jjao
- name: StakedTech
  stash: 12H9FfSYdQ4GrKc7tdxK8U6DitAZMqfnhB8gtHwd2rpCiZfN
  kusamaStash: FFRsm3haD645qfSVE1zfywYURWQ6z7YUAD4nad6Zw6qVxDk
- name: tsuki-validator-0
  stash: 14zGLKbiqsLHLoiT1vh7rEr556EW14Sci3dzv426eLSjapTR
  kusamaStash: D3GpUSsNEnabe5mX8bCkq8Nnc9FVsZgb9nBbTjBq8t52GBg
- name: Saxemberg
  stash: 153YD8ZHD9dRh82U419bSCB5SzWhbdAFzjj4NtA5pMazR2yC
  kusamaStash: J19LYGghRCe4Ct3VW4Vz1amMoUgogS1sh2FQvPWroKcDdb1
- name: Binary Holdings 0001
  stash: 13UQKb6cQ3cvDTdMRTDcydUBmJ3cSYp64Y8R7Zenc29NZ39x
  kusamaStash: HDbZDq8aW1pDbgzQcGK9Mzr8FnrRWHsoiXMSBVnoLwzy7HC
- name: redpenguin
  stash: 15KDFYfFjdqhp3MDFEtHuyu9kLpXbT7k1zjx78MphViFdCaU
  kusamaStash: G7mWyu1Pom5XreLHUzDEcvFp6WaMuLuo4QKxtDB9yJZnH69
- name: Ondin
  stash: 13ond4N8gejhNeYFxAiCtDymHvgsyQMW3L2kvKMEPtmvi3Cu
  kusamaStash: HWAGAxX2PAzNVg7w3ZyTprH5yvwbVwQ8rbWwuZxtQKbQupW
- name: uc3r
  stash: 14uLDf9HaQAu9FM6qpBNv57CJKjg1rcuMcZz8aAxQ9qvM45v
  kusamaStash: GUejeE6LyvMTNA2eswRfse3bJ2G8DswjVgFMwTZKs2tuiod
- name: prematurata
  stash: 155tk9HmeJGsNZtA5LFasSCGZCdpAb2P2Gs6ej9JeP38sAww
  kusamaStash: H72hS8xLmSiSBqbBXHND2KbN8PAoevi52B685cbGki6T9nt
- name: Filimonov
  stash: 15o1NpLSaBbRFwxxtwauyRYMULR2Maa34JeTzFVNWZzamoYV
  kusamaStash: HNKtoRFLmLsa4mti1LxjE5CmJhcTwq5SBkjDcmySHBZLPir
- name: Nodeasy
  stash: 12dvyqCFhVubTDqMdojyjhkxVUMaYVXWLv8uZW1NomUunPmN
  kusamaStash: CczSz9z41uHpftVviWz91TgjLe3SmbvXfbAc958cjy7F6Qs
- name: 🚀🚀🚀 raketa
  stash: 145TDBrdcbSYGNvDJCpSydiTnygGkT1KBtckxqDZew14dUsB
  kusamaStash: FemjAwSPBBzaVj97GaVjSFK5wxrrpGMZmj2CCWAaeC3C5XJ
- name: COSMOON
  stash: 15CosmEmAfQAhnxwan18e5TueAe6bDzrqqxg13dToDWr7A8M
  kusamaStash: CmjHFdR59QAZMuyjDF5Sn4mwTgGbKMH2cErUFuf6UT51UwS
- name: STAKE-R-US-DOT
  stash: 16S9PjqUFWjQweYymtUQ6GHjjJ6AXX1AQePWJ8gFzrWWcmy2
  kusamaStash: GJFCVN8eVH5x5GJtxscKUt7BX4zoCuDqBKYsPBu1w3Yiq3n
- name: Staker Space-sv-validator-0
  stash: 14N5nJ4oR4Wj36DsBcPLh1JqjvrM2Uf23No2yc2ojjCvSC24
  kusamaStash: FcjmeNzPk3vgdENm1rHeiMCxFK96beUoi2kb59FmCoZtkGF
- name: dakkk
  stash: 12iqwZGB2sguEhjFi2ZRuWWixU8mHJnSiP1pwDefqGsBy4rV
  kusamaStash: HX6qEdgi3eFMasuBwtVFLKKtKVJzHAAK17pLyB7SxkxCASD
- name: OMAJ
  stash: 1jvKCgfrDeuj8aZaDVqbLR3EsbexBbhKo22k1gtydkaKzXU
  kusamaStash: DKEqBmUcoQN3FPVPHFtM8wtXqtF4Yrjhg8HyNyVuLwYtcoa
- name: Sio34
  stash: 16DJbUVKFJp6igLoDxCTPesE2DMgMmiawLXG9jsGpYNTshxt
  kusamaStash: GCzeGccTUJaJSsUHWKaPb5AKiHP8oxm6jJsxDjMbEtNGf2H
- name: 🐰【 CRYPTIDS/FRANK 】🐰
  stash: 1StVBqjDJKogQTsLioHC44iFch1cEAv2jcpsnvsy5buBtUE
  kusamaStash: JDEgrmpP97qu8UoTjm2Ra8wJUrXFrunabsnyQ2bZRspf9r6
- name: Stakin 1
  stash: 14Uu59k5VLBz3zLMaEe3LBcqRLfKw2VJu2D3krxTssREjDJc
  kusamaStash: DDdwYhRXzGWBvvaqMEQ7acJs21FiB96L7nnJZfq6HxseFxW
- name: Mile
  stash: 14tcxHSTAiZf7M4vcLfFdGkGJFjfx6zDqds5QVyz2H24hKgG
  kusamaStash: HMaTJbeYonb2SoT7ek1sjrtkkKaor7j3yy2VUbj6FDokPXr
- name: NotaRaspberryPi
  stash: 15D9vUtZLkCBBqq24134ae11TBEHzwGkaLhAwse7n4ieSxv7
  kusamaStash: JKmFAAo9QbR9w3cfSYxk7zdpNEXaN1XbX4NcMU1okAdpwYx
- name: ilgio
  stash: 15BZW721S3fzMYT8vY3Dt2sVXNTECqwHQ1bNUM8q4fi7EVcc
  kusamaStash: Cdhjt72TSezVDkUzdgyoSwXByfwQJjuXSYcDs5L8snyB8Yx
- name: andreita-validator-0
  stash: 1247Twcyzmb46zNZ68yg3ZBPcsAfKRsxhTa2tkbPBs12gwXt
  kusamaStash: EyTegKZ9DBvMkV6pMbjx2fRk3N2VLNNduuto1PGpYcEqRrX
- name: Pioneer
  stash: 129LBt5T1eYtnGHbPYeiiMdmWfokCiiq7z6JBfjnYifiombz
  kusamaStash: EQF693vsen6WxMdoYgf2cypvH4saFJWFzDupoFUT79MffeW
- name: 🏢 MIDL_dev_1
  stash: 1JoBYyPoUdsuU7vZi3KgQAaQYn6WhKqUDXRDmsaJ8Zgxr4T
  kusamaStash: GyrcqNwF87LFc4BRxhxakq8GZRVNzhGn3NLfSQhVHQxqYYx
- name: tartan-validator-0
  stash: 14dbHVYSvG61HqBMBZVoiYBRT9DwJBZdyxUSuR1XECwsTzdw
  kusamaStash: DzfbhY75AWpqeeQoWhJXZnqr2C9kDjBEkZi4hQbMXTWTkqu
- name: OnFinalityValidator
  stash: 15rb4HVycC1KLHsdaSdV1x2TJAmUkD7PhubmhL3PnGv7RiGY
  kusamaStash: HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP
- name: Allnodes
  stash: 15ML93PH72j5fFfqLrXRy7uDh7pUBCTUcSVYbaDV18LaTfeW
  kusamaStash: DrcpVMV5dExRfYh1vcSgZLBfzW7cKjU18ZktNDqesNEs31B
- name: Melange
  stash: 13XkGCa13arfw4FkH8MVsvshrHrA9GuKPANjZ7xnjKCSg9fM
  kusamaStash: EAhgtgo4qb6tbh3VwrPEgxne9qkwiqg5SzNHTmbqyoVyHk5
- name: KIRA Staking
  stash: 15UyiZ9rYhrX39Rasc1iE4sdME7WHNFSj8RQT3yuuytd3Nrd
  kusamaStash: HhcrzHdB5iBx823XNfBUukjj4TUGzS9oXS8brwLm4ovMuVp
- name: Dionysus-sv-validator-0
  stash: 12CJw9KNkC7FzVVg3dvny4PWHjjkvdyM17mmNfXyfucp8JfM
  kusamaStash: FWz717J6ATaYSNy2tRHAskEC9SP4uKHNJYC9mvfvimkB8GT
- name: stakezone
  stash: 1sEcDfGZsbJCSinFBPN2hkqYU8QwLxipDjuz3BN7UFPJnrk
  kusamaStash: G7Ur4BnMSfP2qE7ruSob5gwGQ5nzkGWu7Yqh14FcMqnDtgB
- name: KODAY
  stash: 15cfSaBcTxNr8rV59cbhdMNCRagFr3GE6B3zZRsCp4QHHKPu
  kusamaStash: DayVh23V32nFhvm2WojKx2bYZF1CirRgW2Jti9TXN9zaiH5
- name: Simply Staking
  stash: 13uwV8CBHjv25W3GACLPzzvTu2v9USc2yCQdhrqPhyM3vx6w
  kusamaStash: DNDBcYD8zzqAoZEtgNzouVp2sVxsvqzD4UdB5WrAUwjqpL8
- name: IL4R141
  stash: 12rgiL4r56kPE4PuYmz8snR21isfbrcp5Vbf8VdJe2AWDuus
  kusamaStash: CmWzMp9is3LgQFWY6qtvkEUft57NXVVbXxKxarHjxPCrTtu
- name: "0x0A-Litentry-Polkadot-Validator"
  stash: 12UGgkdQbhWVRsYBcEJRxxr5Bp75z3AKGKtBiUTjkZR15xzS
  kusamaStash: DaWVnjfH2ACj9g6qRNDHbJMbZQXTVPR7Xguss3HcSHgtWU8
